# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  pull_request:
    types:
      - closed
    branches: [main]

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: false

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  if_merge:
    name: If merge
    runs-on: ubuntu-latest
    if: |
      startsWith(github.head_ref, 'releases/') &&
      github.ref != 'refs/heads/main'
    steps:
      - run: echo "We're on `main` and the PR came from `releases/`"

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - if_merge
    steps:
      - name: Dump environment vars
        run: |
          echo -e "\033[33;1;4mDump environment vars\033[0m"
          echo -e "$(env|sort)\n"
        shell: bash

<<<<<<< HEAD
      - name: Dump all context
        if: ${{ inputs.context == 'all' }}
||||||| c2dc841
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
          show-progress: false
          token: ${{ secrets.TOKEN_TO_TRIGGER_SUBSEQUENT_WORKFLOWS }}

      - name: Cache cargo
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
=======
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          show-progress: false
          token: ${{ secrets.TOKEN_TO_TRIGGER_SUBSEQUENT_WORKFLOWS }}

      - name: Cache cargo
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
>>>>>>> upstream/main
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: |
          echo -e "\033[33;1;4mDump environment vars\033[0m"
          echo -e "$(env|sort)\n"

          echo -e "\033[33;1;4mDump github context\033[0m"
          echo -e "$GITHUB_CONTEXT\n"

          echo -e "\033[33;1;4mDump job context\033[0m"
          echo -e "$JOB_CONTEXT\n"

          echo -e "\033[33;1;4mDump steps context\033[0m"
          echo -e "$STEPS_CONTEXT\n"

          echo -e "\033[33;1;4mDump matrix context\033[0m"
          echo -e "$MATRIX_CONTEXT\n"

          echo -e "\033[33;1;4mDump runner context\033[0m"
          echo -e "$RUNNER_CONTEXT\n"

          echo -e "\033[33;1;4mDump strategy context\033[0m"
          echo -e "$STRATEGY_CONTEXT\n"
        shell: bash
      - name: Upload github release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          tag_name: ${{ steps.release.outputs.version }}
          prerelease: true
          token: ${{ secrets.TOKEN_TO_TRIGGER_SUBSEQUENT_WORKFLOWS }}
